import { NextRequest, NextResponse } from "next/server";
import { requireAuth, isGuardOk } from "@/lib/auth/requireAuth";
import { combinedRateLimit } from "@/lib/security/rateLimit";
import { enforceCsrfProtection } from "@/lib/security/csrf";
import {
  exportRequestSchema,
  validateInput,
  formatZodError,
  ExportFormat,
  ExportRequestInput,
  parseJsonBodyWithinLimit,
  REQUEST_BODY_LIMITS,
} from "@/lib/security/validation";

/**
 * POST /api/export - Export explanation in various formats
 * 
 * Supported formats:
 * - markdown: Markdown document
 * - plain: Plain text
 * - pr_comment: PR comment format (GitHub-friendly)
 * - notion: Notion-friendly blocks
 */
export async function POST(request: NextRequest) {
  try {
    // Check rate limit (more restrictive for exports)
    const rateLimitResponse = await combinedRateLimit(request, "export");
    if (rateLimitResponse) {
      return rateLimitResponse;
    }

    const csrfError = enforceCsrfProtection(request);
    if (csrfError) {
      return csrfError;
    }

    // Require authentication
    const guard = await requireAuth();
    if (!isGuardOk(guard)) {
      return guard;
    }

    const userRateLimitResponse = await combinedRateLimit(request, "export", {
      userId: guard.user.id,
      skipIpCheck: true,
    });
    if (userRateLimitResponse) {
      return userRateLimitResponse;
    }

    const parsedBody = await parseJsonBodyWithinLimit(
      request,
      REQUEST_BODY_LIMITS.EXPORT_BYTES
    );
    if (!parsedBody.ok) {
      return NextResponse.json(parsedBody.body, { status: parsedBody.status });
    }

    const body = parsedBody.data;

    const validation = validateInput(exportRequestSchema, body);
    if (!validation.success) {
      return NextResponse.json(formatZodError(validation.error), { status: 400 });
    }

    const { format, title, pattern, flags, steps, warnings } = validation.data;

    // Generate export content based on format
    const content = generateExport(format, {
      title,
      pattern,
      flags,
      steps,
      warnings,
    });

    return NextResponse.json({ content });
  } catch (error) {
    console.error("Export error:", error);
    return NextResponse.json(
      { error: "internal_error", message: "Failed to generate export" },
      { status: 500 }
    );
  }
}

/**
 * Generate export content in the specified format
 */
function generateExport(
  format: ExportFormat,
  data: Omit<ExportRequestInput, "format">
): string {
  switch (format) {
    case "markdown":
      return generateMarkdown(data);
    case "plain":
      return generatePlainText(data);
    case "pr_comment":
      return generatePRComment(data);
    case "notion":
      return generateNotion(data);
    default:
      return generateMarkdown(data);
  }
}

/**
 * Generate Markdown format
 */
function generateMarkdown(data: Omit<ExportRequestInput, "format">): string {
  const { title, pattern, flags, steps, warnings } = data;
  const lines: string[] = [];

  // Title
  lines.push(`# ${title || "Regex Explanation"}`);
  lines.push("");

  // Pattern
  lines.push("## Pattern");
  lines.push("");
  lines.push("```regex");
  lines.push(`/${pattern}/${flags}`);
  lines.push("```");
  lines.push("");

  // Explanation
  lines.push("## Explanation");
  lines.push("");

  for (const step of steps) {
    const indent = "  ".repeat(step.depth);
    lines.push(`${indent}${steps.indexOf(step) + 1}. ${step.label}`);
    if (step.detail) {
      lines.push(`${indent}   *${step.detail}*`);
    }
  }
  lines.push("");

  // Warnings
  if (warnings && warnings.length > 0) {
    lines.push("## Warnings");
    lines.push("");

    for (const warning of warnings) {
      const icon = getSeverityIcon(warning.severity);
      lines.push(`### ${icon} ${warning.title}`);
      lines.push("");
      lines.push(warning.message);
      if (warning.hint) {
        lines.push("");
        lines.push(`> **Tip:** ${warning.hint}`);
      }
      lines.push("");
    }
  }

  // Footer
  lines.push("---");
  lines.push("*Generated by [RegexLens](https://regexlens.app)*");

  return lines.join("\n");
}

/**
 * Generate plain text format
 */
function generatePlainText(data: Omit<ExportRequestInput, "format">): string {
  const { title, pattern, flags, steps, warnings } = data;
  const lines: string[] = [];

  // Title
  lines.push(title || "Regex Explanation");
  lines.push("=".repeat((title || "Regex Explanation").length));
  lines.push("");

  // Pattern
  lines.push(`Pattern: /${pattern}/${flags}`);
  lines.push("");

  // Explanation
  lines.push("Explanation:");
  lines.push("-".repeat(12));

  for (const step of steps) {
    const indent = "  ".repeat(step.depth);
    lines.push(`${indent}${steps.indexOf(step) + 1}. ${step.label}`);
    if (step.detail) {
      lines.push(`${indent}   (${step.detail})`);
    }
  }
  lines.push("");

  // Warnings
  if (warnings && warnings.length > 0) {
    lines.push("Warnings:");
    lines.push("-".repeat(9));

    for (const warning of warnings) {
      const severity = warning.severity.toUpperCase();
      lines.push(`[${severity}] ${warning.title}`);
      lines.push(`  ${warning.message}`);
      if (warning.hint) {
        lines.push(`  Tip: ${warning.hint}`);
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}


function escapeMarkdownTableCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\r?\n/g, "<br/>");
}

/**
 * Generate PR comment format (GitHub-friendly)
 */
function generatePRComment(data: Omit<ExportRequestInput, "format">): string {
  const { title, pattern, flags, steps, warnings } = data;
  const lines: string[] = [];

  // Collapsible details for PR comments
  lines.push(`<details>`);
  lines.push(`<summary><strong>${title || "Regex Explanation"}</strong></summary>`);
  lines.push("");

  // Pattern
  lines.push("**Pattern:**");
  lines.push("```regex");
  lines.push(`/${pattern}/${flags}`);
  lines.push("```");
  lines.push("");

  // Explanation as a table
  lines.push("**Explanation:**");
  lines.push("");
  lines.push("| Step | Description |");
  lines.push("|------|-------------|");

  for (const [index, step] of steps.entries()) {
    const indent = "&nbsp;".repeat(step.depth * 4);
    const safeLabel = escapeMarkdownTableCell(step.label);
    const detail = step.detail
      ? ` *(${escapeMarkdownTableCell(step.detail)})*`
      : "";
    lines.push(`| ${index + 1} | ${indent}${safeLabel}${detail} |`);
  }
  lines.push("");

  // Warnings
  if (warnings && warnings.length > 0) {
    lines.push("**Warnings:**");
    lines.push("");

    for (const warning of warnings) {
      const icon = getSeverityIcon(warning.severity);
      lines.push(`- ${icon} **${warning.title}**: ${warning.message}`);
    }
    lines.push("");
  }

  lines.push("</details>");
  lines.push("");
  lines.push("*Generated by [RegexLens](https://regexlens.app)*");

  return lines.join("\n");
}

/**
 * Generate Notion-friendly format
 */
function generateNotion(data: Omit<ExportRequestInput, "format">): string {
  const { title, pattern, flags, steps, warnings } = data;
  const lines: string[] = [];

  // Notion uses standard markdown with some extensions
  // Using callouts and toggles

  // Title as heading
  lines.push(`# ${title || "Regex Explanation"}`);
  lines.push("");

  // Pattern in code block
  lines.push("## Pattern");
  lines.push("");
  lines.push("```");
  lines.push(`/${pattern}/${flags}`);
  lines.push("```");
  lines.push("");

  // Explanation as numbered list with toggles
  lines.push("## Explanation");
  lines.push("");

  for (const step of steps) {
    const bullet = step.depth > 0 ? "    ".repeat(step.depth) + "- " : `${steps.indexOf(step) + 1}. `;
    lines.push(`${bullet}${step.label}`);
    if (step.detail) {
      lines.push(`${"    ".repeat(step.depth + 1)}> ${step.detail}`);
    }
  }
  lines.push("");

  // Warnings as callouts
  if (warnings && warnings.length > 0) {
    lines.push("## Warnings");
    lines.push("");

    for (const warning of warnings) {
      const calloutType = getNotionCalloutType(warning.severity);
      lines.push(`> ${calloutType} **${warning.title}**`);
      lines.push(`> ${warning.message}`);
      if (warning.hint) {
        lines.push(`>`);
        lines.push(`> 💡 ${warning.hint}`);
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

/**
 * Get severity icon for markdown
 */
function getSeverityIcon(severity: "info" | "warn" | "danger"): string {
  switch (severity) {
    case "danger":
      return "🔴";
    case "warn":
      return "🟡";
    case "info":
    default:
      return "🔵";
  }
}

/**
 * Get Notion callout type
 */
function getNotionCalloutType(severity: "info" | "warn" | "danger"): string {
  switch (severity) {
    case "danger":
      return "⛔";
    case "warn":
      return "⚠️";
    case "info":
    default:
      return "ℹ️";
  }
}
