import type { ExportFormat, ExportRequestInput } from "@/lib/security/validation";

export type ExportContentInput = Omit<ExportRequestInput, "format">;

/**
 * Generate export content in the specified format
 */
export function generateExport(
  format: ExportFormat,
  data: ExportContentInput
): string {
  switch (format) {
    case "markdown":
      return generateMarkdown(data);
    case "plain":
      return generatePlainText(data);
    case "pr_comment":
      return generatePRComment(data);
    case "notion":
      return generateNotion(data);
    default:
      return generateMarkdown(data);
  }
}

function generateMarkdown(data: ExportContentInput): string {
  const { title, pattern, flags, steps, warnings } = data;
  const lines: string[] = [];

  lines.push(`# ${title || "Regex Explanation"}`);
  lines.push("");
  lines.push("## Pattern");
  lines.push("");
  lines.push("```regex");
  lines.push(`/${pattern}/${flags}`);
  lines.push("```");
  lines.push("");
  lines.push("## Explanation");
  lines.push("");

  steps.forEach((step, index) => {
    const indent = "  ".repeat(step.depth);
    lines.push(`${indent}${index + 1}. ${step.label}`);
    if (step.detail) {
      lines.push(`${indent}   *${step.detail}*`);
    }
  });
  lines.push("");

  if (warnings && warnings.length > 0) {
    lines.push("## Warnings");
    lines.push("");

    for (const warning of warnings) {
      const icon = getSeverityIcon(warning.severity);
      lines.push(`### ${icon} ${warning.title}`);
      lines.push("");
      lines.push(warning.message);
      if (warning.hint) {
        lines.push("");
        lines.push(`> **Tip:** ${warning.hint}`);
      }
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("*Generated by [RegexLens](https://regexlens.app)*");

  return lines.join("\n");
}

function generatePlainText(data: ExportContentInput): string {
  const { title, pattern, flags, steps, warnings } = data;
  const lines: string[] = [];
  const heading = title || "Regex Explanation";

  lines.push(heading);
  lines.push("=".repeat(heading.length));
  lines.push("");
  lines.push(`Pattern: /${pattern}/${flags}`);
  lines.push("");
  lines.push("Explanation:");
  lines.push("-".repeat(12));

  steps.forEach((step, index) => {
    const indent = "  ".repeat(step.depth);
    lines.push(`${indent}${index + 1}. ${step.label}`);
    if (step.detail) {
      lines.push(`${indent}   (${step.detail})`);
    }
  });
  lines.push("");

  if (warnings && warnings.length > 0) {
    lines.push("Warnings:");
    lines.push("-".repeat(9));

    for (const warning of warnings) {
      const severity = warning.severity.toUpperCase();
      lines.push(`[${severity}] ${warning.title}`);
      lines.push(`  ${warning.message}`);
      if (warning.hint) {
        lines.push(`  Tip: ${warning.hint}`);
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

function escapeMarkdownTableCell(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/\|/g, "\\|")
    .replace(/\r?\n/g, "<br/>");
}

function escapeHTML(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function generatePRComment(data: ExportContentInput): string {
  const { title, pattern, flags, steps, warnings } = data;
  const lines: string[] = [];
  const safeTitle = escapeHTML(title || "Regex Explanation");

  lines.push(`<details>`);
  lines.push(`<summary><strong>${safeTitle}</strong></summary>`);
  lines.push("");
  lines.push("**Pattern:**");
  lines.push("```regex");
  lines.push(`/${pattern}/${flags}`);
  lines.push("```");
  lines.push("");
  lines.push("**Explanation:**");
  lines.push("");
  lines.push("| Step | Description |");
  lines.push("|------|-------------|");

  for (const [index, step] of steps.entries()) {
    const indent = "&nbsp;".repeat(step.depth * 4);
    const safeLabel = escapeMarkdownTableCell(step.label);
    const detail = step.detail
      ? ` *(${escapeMarkdownTableCell(step.detail)})*`
      : "";
    lines.push(`| ${index + 1} | ${indent}${safeLabel}${detail} |`);
  }
  lines.push("");

  if (warnings && warnings.length > 0) {
    lines.push("**Warnings:**");
    lines.push("");

    for (const warning of warnings) {
      const icon = getSeverityIcon(warning.severity);
      const safeTitle = escapeHTML(warning.title);
      const safeMessage = escapeHTML(warning.message);
      lines.push(`- ${icon} **${safeTitle}**: ${safeMessage}`);
    }
    lines.push("");
  }

  lines.push("</details>");
  lines.push("");
  lines.push("*Generated by [RegexLens](https://regexlens.app)*");

  return lines.join("\n");
}

function generateNotion(data: ExportContentInput): string {
  const { title, pattern, flags, steps, warnings } = data;
  const lines: string[] = [];

  lines.push(`# ${title || "Regex Explanation"}`);
  lines.push("");
  lines.push("## Pattern");
  lines.push("");
  lines.push("```");
  lines.push(`/${pattern}/${flags}`);
  lines.push("```");
  lines.push("");
  lines.push("## Explanation");
  lines.push("");

  steps.forEach((step, index) => {
    const bullet =
      step.depth > 0 ? "    ".repeat(step.depth) + "- " : `${index + 1}. `;
    lines.push(`${bullet}${step.label}`);
    if (step.detail) {
      lines.push(`${"    ".repeat(step.depth + 1)}> ${step.detail}`);
    }
  });
  lines.push("");

  if (warnings && warnings.length > 0) {
    lines.push("## Warnings");
    lines.push("");

    for (const warning of warnings) {
      const calloutType = getNotionCalloutType(warning.severity);
      lines.push(`> ${calloutType} **${warning.title}**`);
      lines.push(`> ${warning.message}`);
      if (warning.hint) {
        lines.push(`>`);
        lines.push(`> 💡 ${warning.hint}`);
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

function getSeverityIcon(severity: "info" | "warn" | "danger"): string {
  switch (severity) {
    case "danger":
      return "🔴";
    case "warn":
      return "🟡";
    case "info":
    default:
      return "🔵";
  }
}

function getNotionCalloutType(severity: "info" | "warn" | "danger"): string {
  switch (severity) {
    case "danger":
      return "⛔";
    case "warn":
      return "⚠️";
    case "info":
    default:
      return "ℹ️";
  }
}
